      - name: Build APK
        run: |
          cat > buildozer.spec << 'EOF'
          [app]
          title = Leaf Area Meter
          package.name = leafareameter
          package.domain = org.example
          source.dir = .
          source.include_exts = py,png,jpg,kv,atlas
          version = 1.0
          requirements = python3,kivy==2.2.1,camera4kivy==0.4.0,gestalt==0.3.0,numpy==1.26.4,opencv-python-headless==4.9.0.80
          orientation = portrait
          android.permissions = CAMERA, WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE
          android.api = 33
          android.minapi = 24
          android.ndk = 25c
          android.features = android.hardware.camera, android.hardware.camera.autofocus
          p4a.branch = develop
          android.native_build_tools = ndk-build
          p4a.extra_args = --no-copy-libs
          EOF
          
          export ANDROIDSDK="$HOME/.buildozer/android/platform/android-sdk"
          export ANDROIDAPI=33
          export ANDROIDMINAPI=24
          # Ігноруємо помилку clang
          export CFLAGS="-Wno-error=unused-command-line-argument"
          export CXXFLAGS="-Wno-error=unused-command-line-argument"
          
          buildozer -v android debug
